# Generated by Django 5.1.3 on 2026-03-29 06:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='agenda',
            index=models.Index(fields=['project', 'status'], name='agenda_project_status_idx'),
        ),
        migrations.AddIndex(
            model_name='agenda',
            index=models.Index(fields=['assigned_to', 'deadline'], name='agenda_assigned_deadline_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['status'], name='client_status_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['email'], name='client_email_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status', 'created_at'], name='project_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['created_by', 'status'], name='project_created_by_status_idx'),
        ),
    ]
