# Generated by Django 5.1.3 on 2024-12-25 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_remove_expense_status_alter_expense_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='receipt2',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='expense',
            name='receipt3',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='expense',
            name='receipt4',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
