# Generated by Django 5.1.3 on 2024-12-27 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0005_expenseauditlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenseauditlog',
            name='expense',
        ),
        migrations.AddField(
            model_name='expenseauditlog',
            name='expense_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expenseauditlog',
            name='expense_title',
            field=models.CharField(default='ggg', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expenseauditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Updated'), ('DELETE', 'Deleted')], max_length=10),
        ),
    ]
