# Generated by Django 5.1.3 on 2026-03-29 06:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0006_remove_expenseauditlog_expense_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['created_by', 'expense_date'], name='expense_user_date_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['created_by', 'category'], name='expense_user_category_idx'),
        ),
        migrations.AddIndex(
            model_name='expenseauditlog',
            index=models.Index(fields=['expense_id'], name='auditlog_expense_id_idx'),
        ),
        migrations.AddIndex(
            model_name='expenseauditlog',
            index=models.Index(fields=['user', 'timestamp'], name='auditlog_user_timestamp_idx'),
        ),
    ]
